# region org.gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=false
# endregion
########################################################################################################################
# region mod
mod.group=io.github.leawind.thirdperson
mod.id=leawind_third_person
mod.version=3.0.0-alpha.1
mod.name=Leawind's Third Person
mod.description=A practical, smooth, feature-rich third-person mod.
mod.author=Leawind
mod.license=MIT
mod.logo_file=logo.png
mod.home_url=https://leawind.github.io/Third-Person/en_us/?autolang
mod.source_url=https://github.com/Leawind/Third-Person
mod.issues_url=https://github.com/Leawind/Third-Person/issues
# endregion
########################################################################################################################
# region dependencies
mod.perspective_api_version=1.2.0-beta
deps.fabricLoader=0.19.3
# endregion
