# region org.gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.caching.debug=false
org.gradle.configureondemand=false
# endregion
########################################################################################################################
# region mod
mod.group=com.github.leawind.thirdperson
mod.id=leawind_third_person
mod.version=2.5.0
mod.name=Leawind's Third Person
mod.description=A practical, smooth, feature-rich third-person mod.
mod.author=Leawind
mod.license=MIT
mod.logo_file=assets/leawind_third_person/logo.png
mod.home_url=https://leawind.github.io/Third-Person/en-US/?autolang
mod.source_url=https://github.com/Leawind/Third-Person
mod.issues_url=https://github.com/Leawind/Third-Person/issues
########################################################################################################################
# Dependency versions
# https://modrinth.com/mod/architectury-api/versions
mod.architectury_api_version=20.0.9
# https://fabricmc.net/develop/
mod.fabric_api_version=0.155.2+26.1.2
# https://github.com/LlamaLad7/MixinExtras/releases
mod.mixinextras_version=0.5.4
# https://modrinth.com/mod/cloth-config/versions
mod.cloth_config_api_version=26.1.154
# https://modrinth.com/mod/yacl/versions
mod.yacl_mc_version=3.9.5+26.1
# https://modrinth.com/mod/modmenu/versions
mod.modmenu_version=18.0.0
# endregion
