modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${mod_url_issue}"
license = "${mod_license}"

[[mods]]
modId = "leawind_third_person"
version = "${version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "Leawind"
logoFile = "TODO"
displayURL = "${mod_url_home}"

[[dependencies.leawind_third_person]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.leawind_third_person]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version_min},${minecraft_version_max}]"
ordering = "NONE"
side = "CLIENT"
referraUrl = "https://www.minecraft.net/"

[[dependencies.leawind_third_person]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
referraUrl = "https://modrinth.com/mod/architectury-api"

[[dependencies.leawind_third_person]]
modId = "cloth_config"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
referraUrl = "https://modrinth.com/mod/cloth-config"

[[mixins]]
config = "leawind_third_person.mixins.json"

[[mixins]]
config = "leawind_third_person-common.mixins.json"
